apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: api-todo
    tier: database
spec:
  ports:
    - port: 27017
  selector: 
    app: api-todo
    tier: database
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db
  labels: 
    app: api-todo
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: database
  labels:
    app: api-todo
    tier: database
spec:
  selector:
    matchLabels:
      app: api-todo
      tier: database  
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-todo
        tier: database
    spec:
      containers:
      - image: mongo
        name: database-cont
        volumeMounts: 
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-db
