apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: api-todo
    tier: node-api
spec:
  selector:
    app: api-todo
    tier: node-api
  type: LoadBalancer
  ports:
  - nodePort: 30534
    port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-todo
      tier: node-api
  template:
    metadata:
      labels:
        app: api-todo
        tier: node-api
    spec:
      containers:
      - image: smc181002/api-todo
        name: node-api
